import Head from 'next/head'
import Layout from '../components/Home/Layout'

export default function Home() {
  return (
    <>
      <Head>
        <title>Home - The Metropolitan Museum of Art</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout />
    </>
  )
}
